### ISSUE TITLE
[DOCKER] Simple mongodb service

### ISSUE THREAD

**Issue by heavenbean** [heavenbean/RnD#14]
```
version: '3.8'

volumes:
  mongodb_vol:
    driver: local

services:
  db:
    image: mongo:5.0.6
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_vol:/data/db
    restart: unless-stopped
    stdin_open: true
    tty: true
```
