### ISSUE TITLE
[DOCKER] Ubuntu 22.04

### ISSUE THREAD

**Issue by heavenbean** [heavenbean/RnD#26]
```
version: "3"
services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:22.04
    restart: on-failure
    command: ["sleep","infinity"]
    volumes:
      - ./virtual-ubuntu:/usr/storage
    ports:
      - 8080:8080
      - 3000:3000
      - 3100:3100
```
